server:
  port: 5555
  
spring:
  application:
    name: microservice-gateway-zuul-filter
  
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka  # http://localhost:8761/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
     
logging:
  pattern:
    level: info