server:
  port: 6666
  
spring:
  application:
    name: microservice-sidecar
  
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka  # http://localhost:8761/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
     
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json