server:
  port: 2222
  
spring:
  application:
    name: microservice-consumer-movie

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka # http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}