eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:1001/eureka/
server:
  port: 9002
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#spring:
#  zipkin:
#    base-url: http://localhost:9411
