

spring:
  profiles:
    active: peer2
  application:
    name: eureka-server-ha
security:
  basic:
    enabled: true
  user:
    name: fuyi
    password: 123456

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://fuyi:123456@peer2:1002/eureka/
server:
  port: 1001

---

spring:
  profiles: peer2
  application:
    name:
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://fuyi:123456@peer1:1001/eureka/
server:
  port: 1002