server:
  port: 3333
#  context-path: /ribbon
  
spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix # issue 281

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka # http://localhost:8761/eureka/
  instance:
    # metadata-map:
      # management.port: ${management.port:8081} # actuator 的端口
    prefer-ip-address: true
    # home-page-url-path: /ribbon
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000