server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false # 配置不作为eureka client,默认eureka server会自带client用来和其他server通信
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka