server:
  port: 7777
  
security:
  basic:
    enabled: true
  user:
    name: fuyi
    password: pwd
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/fuyiyi/{application} # {application}-{profile}
  application:
    name: config-server
          
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# 对称加密key,盐
# encrypt:
  # key: fuyi
  
# 非对称加密
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme