server:
  port: 7777
  
security:
  basic:
    enabled: true
  user:
    password: pwd
  
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

# 注册到eureka server     
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
